name: Smoketest / Informative / Ubuntu
on:
  pull_request:
  merge_group:

jobs:
  test:
    name: Compilers
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ubuntu:
          - "22.04" # LTS only for sanity
        compiler:
          - g++
          - clang
    container: ubuntu:${{ matrix.ubuntu }}
    steps:
      - name: Install Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get -qq update
          apt-get -qq upgrade -y
          apt-get -qq install -y --no-install-recommends \
            ca-certificates \
            git \
            ${{ matrix.compiler }} \
            cmake \
            make \
            ccache \
            libboost-dev \
            libboost-filesystem-dev \
            libboost-locale-dev \
            libboost-regex-dev \
            libboost-system-dev \
            libcairo2-dev \
            libglew-dev \
            libglm-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libvorbis-dev

      - name: Checkout Anura
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: true

      - name: Set ccache up
        uses: hendrikmuhs/ccache-action@ca3acd2731eef11f1572ccb126356c2f9298d35e # v1.2.9
        with:
          key: ${{ github.job }}-ubuntu-${{ matrix.ubuntu }}-${{ matrix.compiler }}

      - name: Build Anura
        env:
          CXX: ${{ matrix.compiler }}
        # Compile with number of available hyperthreads
        run: |
          cmake .
          make -j "$(getconf _NPROCESSORS_ONLN)"

      - name: Run Unit Tests
        run: ./anura --tests
