name: Smoketest / Informative / Fedora
on:
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday

jobs:
  test:
    name: Compilers
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        fedora:
          # Fedora 33 is the oldest Fedora with a new enough CMake for our FetchContent workarounds
          - "33"
          - "34"
          - "35"
          - "36"
          - "37"
          - "38"
          - "39"
          - "40"
          - "41"
          - "42"
          - "43"
          - "44"
          # 45 is expected in 2026-11
          # 46 is expected in 2027-04
        compiler:
          - g++
          - clang++
        build-type:
          - Release
          - Debug
    container: fedora:${{ matrix.fedora }}
    steps:
      - name: Install Dependencies
        run: |
          dnf -qy update
          dnf -qy install \
              git \
              g++ \
              clang \
              cmake \
              make \
              ccache \
              boost-devel \
              cairo-devel \
              glew-devel \
              libvorbis-devel \
              SDL2_image-devel \
              SDL2_mixer-devel \
              SDL2_ttf-devel \
              SDL2-devel

      - name: Checkout Anura
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Only write to cache on scheduled builds on trunk
      # Don't restore when creating and saving cache
      - name: Set ccache up
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2.20
        with:
          key: ${{ github.job }}-fedora-${{ matrix.fedora }}-${{ matrix.compiler }}-${{ matrix.build-type }}
          append-timestamp: false
          save: ${{ github.event_name == 'schedule' && github.ref == 'refs/heads/trunk' }}
          restore: ${{ ! (github.event_name == 'schedule' && github.ref == 'refs/heads/trunk') }}

      - name: Build Prep Anura
        run: |
          cmake buildsystem/linux-dynamic \
            --preset="${{ matrix.build-type }}" \
            -D CMAKE_CXX_COMPILER="${{ matrix.compiler }}"

      - name: Build Anura
        run: |
          # Compile with number of available hyperthreads
          cmake \
            --build buildsystem/linux-dynamic/build/"${{ matrix.build-type }}" \
            --parallel "$(getconf _NPROCESSORS_ONLN)"

      - name: Run Unit Tests
        run: |
          ctest \
            --output-on-failure \
            --test-dir buildsystem/linux-dynamic/build/"${{ matrix.build-type }}" \
            -L unittest
