name: Unit Tests / Required / Static / Linux
on:
  pull_request:
  merge_group:
  push:
    branches:
      - trunk
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  build:
    name: Build and Test in Steam SDK
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # XXX - This matrix needs to stay in sync with the test job below!
        compiler:
          # Only g++ builds actually work currently
          - g++
        build-type:
          - Release
          - Debug
        steam-runtime:
          # - scout v1 - Debian Stretch  / 9 - has a glibc too old for Github Actions / Node 20
          # - soldier v2 - Debian Buster / 10 - has a weird compiler and a weird ld, no idea what is up there
          - sniper # v3 - Debian Bullseye / 11
          # - medic v4 - Debian Bookworm / 12 - not in the container registry yet
          # - ??? v5 - Debian Trixie / 13 - not in the container registry yet
    container: registry.gitlab.steamos.cloud/steamrt/${{ matrix.steam-runtime }}/sdk
    steps:
      - name: Install Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo ln -fs /usr/share/zoneinfo/UTC /etc/localtime
          sudo dpkg-reconfigure --frontend=noninteractive tzdata
          sudo apt-get -qq update
          sudo apt-get -qq upgrade -y
          sudo apt-get -qq --no-install-recommends install -y \
            python3-venv \
            libfontenc-dev \
            libxmuu-dev \
            libxres-dev

      - name: Checkout Anura
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Ignore Filesystem Permissions for Git
        run: git config --global --add safe.directory '*'

      # Only write to cache on pushes to trunk
      - name: Set ccache up
        uses: hendrikmuhs/ccache-action@bfa03e1de4d7f7c3e80ad9109feedd05c4f5a716 # v1.2.19
        with:
          key: unit-tests-linux-static-steam-${{ matrix.build-type }}-${{ matrix.compiler }}-${{ matrix.steam-runtime }}
          save: ${{ (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/trunk' }}

      - name: Install Conan
        uses: conan-io/setup-conan@09566912d661de90608308897a4d513e850c04e8 # v1.2.0
        with:
          use_venv: true

      # Always restore cache
      - name: Restore Conan Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.conan2/p
          key: conan-linux-static-steam-${{ matrix.build-type }}-${{ matrix.compiler }}-${{ matrix.steam-runtime }}
          restore-keys: |
            conan-linux-static-steam-${{ matrix.build-type }}-${{ matrix.compiler }}-${{ matrix.steam-runtime }}-

      - name: Install Dependencies with Conan
        run: |
          # XXX - We need to force build b2 as Conan assumes a too new libc++
          conan install buildsystem/conan \
            -s build_type="${{ matrix.build-type }}" \
            -s compiler.cppstd=17 \
            --build='b2/*' \
            --build=missing

      # Only write to cache on pushes to trunk
      - name: Save Conan Cache
        if: github.event_name == 'push' && github.ref == 'refs/heads/trunk'
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.conan2/p
          key: conan-linux-static-steam-${{ matrix.build-type }}-${{ matrix.compiler }}-${{ matrix.steam-runtime }}

      - name: Build Prep Anura
        run: |
          cmake buildsystem/linux-steam \
            --preset="${{ matrix.build-type }}" \
            -D CMAKE_CXX_COMPILER="${{ matrix.compiler }}"

      - name: Build Anura
        run: |
          # Compile with number of available hyperthreads
          cmake \
            --build buildsystem/linux-steam/build/"${{ matrix.build-type }}" \
            --parallel "$(getconf _NPROCESSORS_ONLN)"

      - name: Run Unit Tests
        run: |
          ctest \
            --output-on-failure \
            --test-dir buildsystem/linux-steam/build/"${{ matrix.build-type }}" \
            -L unittest

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: anura-static-binary-${{ matrix.build-type }}-${{ matrix.steam-runtime }}-${{ matrix.compiler }}-${{ github.sha }}
          path: buildsystem/linux-steam/build/${{ matrix.build-type }}/anura
          if-no-files-found: error

  test:
    name: Test on Steam Platform
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # XXX - This matrix needs to stay in sync with the build job above!
        compiler:
          # Only g++ builds actually work currently
          - g++
        build-type:
          - Release
          - Debug
        steam-runtime:
          # - scout v1 - Debian Stretch  / 9 - has a glibc too old for Github Actions / Node 20
          # - soldier v2 - Debian Buster / 10 - has a weird compiler and a weird ld, no idea what is up there
          - sniper # v3 - Debian Bullseye / 11
          # - medic v4 - Debian Bookworm / 12 - not in the container registry yet
          # - ??? v5 - Debian Trixie / 13 - not in the container registry yet
    container: registry.gitlab.steamos.cloud/steamrt/${{ matrix.steam-runtime }}/platform
    steps:
      - name: Checkout Anura
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: anura-static-binary-${{ matrix.build-type }}-${{ matrix.steam-runtime }}-${{ matrix.compiler }}-${{ github.sha }}

      - name: Run Unit Tests
        run: |
          chmod +x anura
          ./anura --tests
