name: Unit Tests / Required / Static / Windows
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  build:
    name: Build and Test on Windows
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Release
          - Debug
    steps:
      - name: Checkout Anura
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Only write to cache on scheduled builds on trunk
      - name: Set ccache up
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2.20
        with:
          key: unit-tests-windows-${{ matrix.build-type }}
          save: ${{ github.event_name == 'schedule' && github.ref == 'refs/heads/trunk' }}

      - name: Install Conan
        uses: conan-io/setup-conan@09566912d661de90608308897a4d513e850c04e8 # v1.2.0
        with:
          use_venv: true

      # Always restore cache
      - name: Restore Conan Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: '%USERPROFILE%\.conan2\p'
          key: conan-windows-static-${{ matrix.build-type }}
          restore-keys: |
            conan-windows-static-${{ matrix.build-type }}-

      - name: Install Dependencies with Conan
        run: |
          conan install buildsystem/conan `
            -s build_type="${{ matrix.build-type }}" `
            -s compiler.cppstd=17 `
            --build=missing

      # Only write to cache on scheduled builds on trunk
      - name: Save Conan Cache
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/trunk'
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: '%USERPROFILE%\.conan2\p'
          key: conan-windows-static-${{ matrix.build-type }}

      - name: Build Prep Anura
        run: |
          cmake buildsystem/windows-static `
            --preset="${{ matrix.build-type }}"

      - name: temp show
        run: dir

      - name: Build Anura
        run: msbuild -m anura.sln

      - name: temp show
        run: dir
