name: Unit Tests / Required / Dynamic / Linux
on:
  pull_request:
  merge_group:
  push:
    branches:
      - trunk
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  test:
    name: Ubuntu
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        build-type:
          - Release
          - Debug
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Install Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq upgrade -y
          sudo apt-get -qq install -y --no-install-recommends \
            ca-certificates \
            git \
            clang \
            cmake \
            make \
            ccache \
            libboost-dev \
            libboost-filesystem-dev \
            libboost-locale-dev \
            libboost-regex-dev \
            libboost-system-dev \
            libcairo2-dev \
            libglew-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libvorbis-dev

      - name: Checkout Anura
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      # Only write to cache on pushes to trunk
      - name: Set ccache up
        uses: hendrikmuhs/ccache-action@bfa03e1de4d7f7c3e80ad9109feedd05c4f5a716 # v1.2.19
        with:
          key: unit-tests-linux-${{ matrix.build-type }}-${{ matrix.runner }}
          save: ${{ (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/trunk' }}

      - name: Build Prep Anura
        run: |
          cmake buildsystem/linux-dynamic \
            --preset="${{ matrix.build-type }}" \
            -D CMAKE_CXX_COMPILER="clang++"

      - name: Build Anura
        run: |
          # Compile with number of available hyperthreads
          cmake \
            --build buildsystem/linux-dynamic/build/"${{ matrix.build-type }}" \
            --parallel "$(getconf _NPROCESSORS_ONLN)"

      - name: Run Unit Tests
        run: |
          ctest \
            --output-on-failure \
            --test-dir buildsystem/linux-dynamic/build/"${{ matrix.build-type }}" \
            -L unittest
