name: Unit Tests / Required / Static / Linux
on:
  pull_request:
  merge_group:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday

jobs:
  build:
    name: Build and Test in Steam SDK
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # XXX - This matrix needs to stay in sync with the test job below!
        compiler:
          # Only g++ builds actually work currently
          - g++
        build-type:
          - Release
          - Debug
        steam-runtime:
          # - scout v1 - Debian Stretch  / 9 - has a glibc too old for Github Actions / Node 20
          # - soldier v2 - Debian Buster / 10 - has a weird compiler and a weird ld, no idea what is up there
          - sniper # v3 - Debian Bullseye / 11
          # - medic v4 - Debian Bookworm / 12 - not in the container registry yet
          # - ??? v5 - Debian Trixie / 13 - not in the container registry yet
    container: registry.gitlab.steamos.cloud/steamrt/${{ matrix.steam-runtime }}/sdk
    steps:
      - name: Install Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo ln -fs /usr/share/zoneinfo/UTC /etc/localtime
          sudo dpkg-reconfigure --frontend=noninteractive tzdata
          sudo apt-get -qq update
          sudo apt-get -qq upgrade -y
          sudo apt-get -qq --no-install-recommends install -y \
            python3-venv \
            libfontenc-dev \
            libxmuu-dev \
            libxres-dev

      - name: Checkout Anura
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Ignore Filesystem Permissions for Git
        run: git config --global --add safe.directory '*'

      # Only write to cache on scheduled builds on trunk
      # Don't restore when creating and saving cache
      - name: Set ccache up
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2.20
        with:
          key: unit-tests-linux-static-steam-${{ matrix.build-type }}-${{ matrix.compiler }}-${{ matrix.steam-runtime }}
          append-timestamp: false
          save: ${{ github.event_name == 'schedule' && github.ref == 'refs/heads/trunk' }}
          restore: ${{ ! (github.event_name == 'schedule' && github.ref == 'refs/heads/trunk') }}

      - name: Install Conan
        uses: conan-io/setup-conan@2f4bd34e8e0af00e1a77a66e1d284e06d71d703f # v1.3.0
        with:
          use_venv: true

      # Don't restore when creating and saving cache
      - name: Restore Conan Cache
        if: ${{ ! (github.event_name == 'schedule' && github.ref == 'refs/heads/trunk') }}
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.conan2/p
          key: conan-linux-static-steam-${{ matrix.build-type }}-${{ matrix.compiler }}-${{ matrix.steam-runtime }}

      - name: Install Dependencies with Conan
        run: |
          # XXX - We need to force build b2 as Conan assumes a too new libc++
          conan install buildsystem/conan \
            -s build_type="${{ matrix.build-type }}" \
            -s compiler.cppstd=17 \
            --build='b2/*' \
            --build='m4/*' \
            --build=missing

      # Only write to cache on scheduled builds on trunk
      - name: Save Conan Cache
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/trunk'
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.conan2/p
          key: conan-linux-static-steam-${{ matrix.build-type }}-${{ matrix.compiler }}-${{ matrix.steam-runtime }}

      - name: Build Prep Anura
        run: |
          cmake buildsystem/linux-steam \
            --preset="${{ matrix.build-type }}" \
            -D CMAKE_CXX_COMPILER="${{ matrix.compiler }}"

      - name: Build Anura
        run: |
          # Compile with number of available hyperthreads
          cmake \
            --build buildsystem/linux-steam/build/"${{ matrix.build-type }}" \
            --parallel "$(getconf _NPROCESSORS_ONLN)"

      - name: Run Unit Tests
        run: |
          ctest \
            --output-on-failure \
            --test-dir buildsystem/linux-steam/build/"${{ matrix.build-type }}" \
            -L unittest

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: anura-static-binary-${{ matrix.build-type }}-${{ matrix.steam-runtime }}-${{ matrix.compiler }}-${{ github.sha }}
          path: buildsystem/linux-steam/build/${{ matrix.build-type }}/anura
          if-no-files-found: error

  test:
    name: Test on Steam Platform
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # XXX - This matrix needs to stay in sync with the build job above!
        compiler:
          # Only g++ builds actually work currently
          - g++
        build-type:
          - Release
          - Debug
        steam-runtime:
          # - scout v1 - Debian Stretch  / 9 - has a glibc too old for Github Actions / Node 20
          # - soldier v2 - Debian Buster / 10 - has a weird compiler and a weird ld, no idea what is up there
          - sniper # v3 - Debian Bullseye / 11
          # - medic v4 - Debian Bookworm / 12 - not in the container registry yet
          # - ??? v5 - Debian Trixie / 13 - not in the container registry yet
    container: registry.gitlab.steamos.cloud/steamrt/${{ matrix.steam-runtime }}/platform
    steps:
      - name: Checkout Anura
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: anura-static-binary-${{ matrix.build-type }}-${{ matrix.steam-runtime }}-${{ matrix.compiler }}-${{ github.sha }}

      - name: Run Unit Tests
        run: |
          chmod +x anura
          ./anura --tests
